### ISSUE TITLE
i have issue on this implemenation 

### ISSUE THREAD

**Issue by majumajid** [Martynnw/AndroidDemos#1]
i have created issue ticket  , kindly help me to fix the issue 
https://github.com/xamarin/Xamarin.Forms/issues/5916
https://github.com/NLog/NLog/issues/3308

**Comment by majumajid** [comment]
i have updated VS2017 to 15.9.11 , issue fixed by updating VS2017.
Thank you so much for your great support

**Comment by Martynnw** [comment]
Closed as user error.
